version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/source/reference/api ytmusicapi

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats: all
